-- Find tables related to payment details or job costs
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%PAYDET%' 
   OR TABLE_NAME LIKE '%DETAIL%'
   OR TABLE_NAME LIKE '%JOBCOST%'
   OR TABLE_NAME LIKE '%TRANS%'
ORDER BY TABLE_NAME;
