-- Use this to discover the exact column names in your Yardi database
SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'DETAIL'
ORDER BY COLUMN_NAME;

-- And for the PAYDET (AP Invoice) table:
SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'PAYDET'
ORDER BY COLUMN_NAME;

-- And for the CATEGORY table:
SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'CATEGORY'
ORDER BY COLUMN_NAME;
